#!/bin/bash
cd /Users/andtsa/PycharmProjects/AoC || exit
x=$(ls -l | grep -c ^d)
x=$((x-1))
echo initialising day $x
mkdir day$x
cd day$x
touch day${x}.txt
touch day${x}test.txt
( head -16 ../template.txt ) > day${x}.py
echo ready!